use_frameworks!

platform :ios, '8.0'

target 'WZNetWork_Example' do
  pod 'WZNetWork', :path => '../'

  target 'WZNetWork_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
