use_frameworks!

xcodeproj 'HZFrameWork.xcodeproj'
target 'HZFrameWork_Example' do
  pod 'HZFrameWork', :path => '../'
  

  target 'HZFrameWork_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
